# -*- coding: utf-8 -*-
"""skill_matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXrrEY4gsDkw6zg5bla-CxKhUMwoyPf8
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df=pd.read_csv("skills_dataset.csv")
vectorizer=TfidfVectorizer()
tfidf_matrix=vectorizer.fit_transform(df["job_title"])
print(tfidf_matrix)

def suggest_skills(job_title, user_skills):
  user_vec = vectorizer.transform([job_title])
  similarities = cosine_similarity(user_vec, tfidf_matrix)
  best_index = similarities.argmax()
  best_score = similarities.max()
  if best_score < 0.2:
    return []
  matched_job = df.iloc[best_index]
  skills = matched_job["skills"].split(",")
  filtered_skills = []
  for skill in skills:
    if skill not in user_skills:
        filtered_skills.append(skill)
  return filtered_skills